language: php

php:
  - '7.2'

services:
  - docker

install:
  - cp .env.dist .env
  - docker-compose up --build -d
  - docker-compose ps

script:
  # Compile assets, and make sure nothing's changed in Git.
  - travis_retry docker-compose exec assets npm run assets
  - git status
  - git status | grep "nothing to commit, working tree clean"
  # Run linting. The LESS and ESlint are run separately here because Composer requires PHP and so we can't run.
  - docker-compose exec web composer lint
  - docker-compose exec assets npm run lint
  # Run tests.
  - docker-compose exec web composer test

after_success:
  - docker-compose exec web vendor/bin/php-coveralls --coverage_clover=var/log/phpunit_clover.xml --json_path=var/coveralls-upload.json
