version: '3'
services:
    web:
        build: ./
        container_name: svgtranslate_web
        ports:
          - ${TOOLFORGE_DOCKER_PORT}:80
        volumes:
          - ./.docker/lighttpd.conf:/etc/lighttpd/lighttpd.conf:cached
          - ./:/var/www:cached
        environment:
          TOOLFORGE_DOCKER_PORT: ${TOOLFORGE_DOCKER_PORT}
