version: '3'
services:

    web:
        build:
            dockerfile: ./.docker/web/Dockerfile
            context: .
        ports:
            - 8042:80
        volumes:
            - ./:/var/www:cached

    assets:
        image: node:11.5
        working_dir: /svgtranslate
        volumes:
            - ./:/svgtranslate:cached
        command: ./.docker/assets/run.sh
