version: '3'
services:
    web:
        build: ./
        container_name: svgtranslate_web
        ports:
          - 8042:80
        volumes:
          - ./.docker/lighttpd.conf:/etc/lighttpd/lighttpd.conf:cached
          - ./:/var/www:cached
